---
title: "Analysis"
format: html
---

```{r}
# Packages
library(scales)
library(knitr)
library(patchwork)
library(ggh4x)
library(brms)
library(ggstance)
library(bayestestR)
library(tidyverse)

# Plotting theme
theme_set(
  theme_linedraw(
    base_size = 9,
    # base_family = Font
  ) +
    theme(
      panel.grid = element_blank(),
      strip.text = element_text(margin = margin(4, 4, 4, 4, "pt")),
      axis.text = element_text(size = rel(0.75))
    )
)
W <- 24

# For ordering outcomes
oo <- c(
  "Life_satisfaction", "Negative_experiences", "Positive_experiences"
)

# Directories for files
dir.create("models", FALSE)
dir.create("out", FALSE)
```

## Prepare data

```{r}
# Load and merge processed data
d_fb <- read_csv("data/fb.csv")
d_gwp <- read_rds("data/gwp.rds") 
# d_gwp <- read_rds("data/gwp-SYNTHETIC.rds") # If real data not available
d_gwp <- d_gwp %>% 
  mutate(outcome = factor(outcome, levels = oo))
d_pop <- read_rds("data/population.rds")

# Convert fb metrics into country-year proportions
d_fb <- d_fb %>% 
  left_join(d_pop) %>% 
  mutate(
    dau = dau / pop,
    mau = mau / pop
  )

# Merge
d <- left_join(d_gwp, d_fb) %>% 
  mutate(age = factor(age, levels = c("13-34", "35+")))
```

## Data figure

```{r}
# Figure of all variables over time
p_a <- d_fb %>% 
  pivot_longer(c(dau, mau), names_to = "outcome", values_to = "val") %>% 
  mutate(outcome = if_else(outcome == "dau", "Daily FB users", "Monthly FB users")) %>% 
  ggplot(aes(year, val, col = age, group = interaction(age, country))) +
  scale_color_brewer(palette = "Dark2") +
  scale_y_continuous(
    "Percentage of population", 
    expand = expansion(.03),
    breaks = extended_breaks(),
    labels = ~percent(.)
  ) +
  scale_x_continuous(
    "Year", 
    breaks = seq(2008, 2018, by = 2), 
    minor_breaks = seq(2009, 2019, by = 2)
  ) +
  geom_line(size = .25) +
  facet_grid(age~outcome) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
  )

p_b <- d %>% 
  select(-c(mau, dau)) %>% 
  # Exclude rows where FB data existed but not GWP data
  drop_na(val) %>% 
  # Actual lowest age in GWP
  mutate(age = factor(age, labels = c("15-34", "35+"))) %>% 
  ggplot(aes(year, val, col = age, group = interaction(age, country))) +
  scale_color_brewer(palette = "Dark2") +
  scale_y_continuous(
    "Value", 
    expand = expansion(.01),
    breaks = extended_breaks()
  ) +
  scale_x_continuous(
    "Year", 
    breaks = seq(2008, 2018, by = 2), 
    minor_breaks = seq(2009, 2019, by = 2)
  ) +
  # Aggregate over sex
  stat_summary(fun = mean, geom = "line", size = .25) +
  facet_grid(age~outcome, labeller = as_labeller(~str_replace(., "_", " "))) +
  theme(legend.position = "none")


p_a / p_b
ggsave("out/Fig-data.png", width = W, height = W*.66, units = "cm", dpi = 400)
```

## Models

```{r}
# Set global contrasts
options(contrasts = c(unordered = "contr.sum", ordered = "contr.poly"))

# Prepare data
dm <- d %>% 
  # Centering predictors
  # Grand mean centering so both components are zero-centered
  mutate(across(c(dau, mau), ~. - mean(., na.rm = TRUE))) %>% 
  group_by(country) %>%
  mutate(
    # Between
    dau_cb = mean(dau, na.rm = TRUE),
    mau_cb = mean(mau, na.rm = TRUE),
    # Within
    dau_cw = dau - dau_cb, 
    mau_cw = mau - mau_cb
  ) %>% 
  ungroup() %>% 
  # Center year so that intercepts are at 2014
  mutate(year = year - 2014) %>% 
  # Remove rows where predictor existed but outcome didn't
  drop_na(val)

# Model formula
model_dau <- bf(
  val | se(se, sigma = TRUE) ~
    (year + dau_cw) * age * sex + dau_cb +
    ((year + dau_cw) * age * sex | country),
  family = gaussian()
)
model_mau <- bf(
  val | se(se, sigma = TRUE) ~
    (year + mau_cw) * age * sex + mau_cb +
    ((year + mau_cw) * age * sex | country),
  family = gaussian()
)

fits <- dm %>% 
  select(outcome, year, country, sex, age, contains("_c"), val, se) %>% 
  group_by(outcome) %>% 
  nest() %>% 
  mutate(
    dau = map2(
      data, outcome,
      ~brm(
        model_dau,
        cores = 8, chains = 4, threads = 2,
        backend = "cmdstanr",
        adapt_delta = .95,
        iter = 3000,
        data = .x,
        file = str_glue("models/brm-dau-{.y}")
      )
    ),
    mau = map2(
      data, outcome,
      ~brm(
        model_mau,
        cores = 8, chains = 4, threads = 2,
        backend = "cmdstanr",
        adapt_delta = .95,
        iter = 3000,
        data = .x,
        file = str_glue("models/brm-mau-{.y}")
      )
    )
  )
```

## Forest plot

```{r}
# Calculate contrasts for each outcome
h_dau <- c(
  "Average" = "dau_cw = 0",
  "13-34" = "dau_cw + dau_cw:age1 * -1 = 0",
  "35+" = "dau_cw + dau_cw:age1 * 1 = 0",
  "Between-country" = "dau_cb = 0"
)
h_mau <- c(
  "Average" = "mau_cw = 0",
  "13-34" = "mau_cw + mau_cw:age1 * -1 = 0",
  "35+" = "mau_cw + mau_cw:age1 * 1 = 0",
  "Between-country" = "mau_cb = 0"
)
coefs <- fits %>% 
  ungroup() %>% 
  pivot_longer(c(dau, mau), names_to = "predictor", values_to = "fit") %>% 
  mutate(h = if_else(predictor == "dau", list(h_dau), list(h_mau))) %>% 
  mutate(
    world = map2(
      fit, h,
      ~hypothesis(.x, .y) %>% 
        .[["hypothesis"]] %>% 
        tibble()
    ),
    country = map2(
      fit, h,
      ~hypothesis(.x, .y, scope = "coef", group = "country") %>% 
        .[["hypothesis"]] %>% 
        tibble()
    )
  ) %>% 
  select(-fit, -h, -data)

coefs <- coefs %>% 
  pivot_longer(c(world, country)) %>% 
  unnest(value) %>% 
  mutate(country = if_else(name == "country", as.character(Group), "World")) %>% 
  mutate(country = fct_relevel(country, "World")) %>% 
  # Between country contrast not country-specific!
  filter(!(Hypothesis == "Between-country" & country != "World"))

# Both predictor and outcome are 0-1, so scale can be interpreted as % change as a function of % change
```


```{r}
coefs %>%   
  filter(Hypothesis %in% c("13-34", "35+")) %>% 
  mutate(
    predictor = if_else(
      predictor == "dau", 
      "Daily FB users", 
      "Monthly FB users"
    )
  ) %>%
  mutate(
    # Order countries on increasing magnitude per panel
    country_order = interaction(predictor, outcome, country),
    country_order = as.numeric(fct_reorder(country_order, Estimate)),
    # But also ensure that average ("World") is in bottom
    country_order = if_else(
      country == "World", country_order-10000, country_order
    ),
    country_order = factor(country_order)
  ) %>% 
  ggplot(aes(Estimate, country_order, col = Hypothesis, shape = Star)) +
  scale_y_discrete("Country", expand = expansion(.015)) +
  scale_x_continuous(
    "Estimated association"
  ) +
  scale_shape_manual(values = c(21, 19)) +
  scale_color_brewer("Age", palette = "Dark2") +
  scale_size_manual(values = c(0.75, 1.5)) +
  geom_vline(xintercept = 0, lty = 2, size = .25, col = "grey50") +
  geom_linerangeh(
    aes(xmin = CI.Lower, xmax = CI.Upper),
    size = .2, position = position_dodgev(.4)
  ) +
  geom_point(
    fill = "white", aes(size = name),
    position = position_dodgev(.4)
  ) +
  facet_grid2(
    predictor~outcome, independent = "all", scales = "free",
    labeller = as_labeller(~str_replace(., "_", " "))
  ) +
  theme(
    axis.text.y = element_blank(),
    legend.position = "none"
  )

ggsave("out/Fig-forest.png", width = W, height = W*.66, units = "cm", dpi = 400)
```

```{r}
# Between-country associations
coefs %>% 
  filter(Hypothesis == "Between-country") %>% 
  select(predictor, outcome, Estimate, CI.Lower, CI.Upper) %>% 
  arrange(predictor, outcome)
  kable()
```

## Conditional effects plot

```{r}
# Create a predictor table with evenly spaced mau_cw values for each country
newx_country <- fits$data[[1]] %>% 
  group_by(country, age, mau_cb) %>% 
  filter(mau_cw %in% c(min(mau_cw), max(mau_cw))) %>% 
  select(country, age, mau_cb, mau_cw) %>% 
  # For above groupings, create a sequence of dau_cws from min to max
  group_modify(
    ~tibble(mau_cw = seq(min(.$mau_cw), max(.$mau_cw), length = 31))
    ) %>% 
  ungroup() %>% 
  mutate(year = 0, se = 0)

newx_world <- fits$data[[1]] %>% 
  group_by(age) %>% 
  filter(mau_cw %in% c(min(mau_cw), max(mau_cw))) %>% 
  select(age, mau_cw) %>% 
  # For above groupings, create a sequence of mau_cws from min to max
  group_modify(
    ~tibble(mau_cw = seq(min(.$mau_cw), max(.$mau_cw), length = 31))
    ) %>% 
  ungroup() %>% 
  mutate(mau_cb = 0, year = 0, se = 0)

newy <- fits %>% 
  mutate(
    country = map(
      mau, 
      ~bind_cols(newx_country, fitted(.x, newx_country))
      ),
    world = map(
      mau, 
      ~bind_cols(newx_world, fitted(.x, newx_world, re_formula = NA))
      )
  ) %>% 
  select(outcome, country, world)
```


```{r}
newy %>% 
  pivot_longer(c(country, world)) %>% 
  unnest(value) %>% 
  ungroup() %>% 
  mutate(country = if_else(name == "world", "World", country)) %>% 
  ggplot(aes(mau_cw, Estimate, group = country, col = age, fill = age)) +
  scale_color_brewer(
    "Age", 
    palette = "Dark2", 
    aesthetics = c("color", "fill")
  ) +
  scale_y_continuous(
    "Estimated outcome",
    breaks = extended_breaks()
  ) +
  scale_x_continuous(
    "Country-mean deviated monthly FB users",
    breaks = extended_breaks(),
    labels = ~percent(.)
  ) +
  scale_size_manual(values = c(.2, .4)) +
  geom_ribbon(
    data = . %>% filter(name == "world"),
    aes(ymin = Q2.5, ymax = Q97.5),
    alpha = .2, col = NA
  ) +
  geom_line(aes(size = name)) +
  facet_grid(
    age~outcome, scales = "free_y",
    labeller = as_labeller(~str_replace(., "_", " "))
  ) +
  theme(legend.position = "none")
ggsave("out/Fig-mau-conditional.png", width = W, height = W*.5, units = "cm", dpi = 400)
```

